---
# control
control:
  data_name: CIFAR10
  model_name: wresnet28x2
  num_clients: '100'
  active_rate: '0.1'
  data_split_mode: 'iid'
  data_poison_method: 'target'
  adversarial_ratio: 'local-0.1' 
  selection_method: 'valid-acc-cluster'
  diff_option: 'no-diff'
# experiment
pin_memory: True
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 1
verbose: True
